2022-10-11 09:57:11,189 DEBUG    root            Loaded Command Group: ['gcloud', 'auth']
2022-10-11 09:57:11,199 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'application_default']
2022-10-11 09:57:11,556 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'application-default', 'login']
2022-10-11 09:57:11,569 DEBUG    root            Running [gcloud.auth.application-default.login] with arguments: [--project: "walica-line-mini-app"]
2022-10-11 09:57:11,649 DEBUG    requests_oauthlib.oauth2_session Generated new state ZowS3YLt2e1G0Dmq2uQfXVF1THiABH.
2022-10-11 09:57:11,653 INFO     ___FILE_ONLY___ You are authorizing client libraries without access to a web browser. Please run the following command on a machine with a web browser and copy its output back here. Make sure the installed gcloud version is 372.0.0 or newer.

gcloud auth application-default login --remote-bootstrap="https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&state=ZowS3YLt2e1G0Dmq2uQfXVF1THiABH&access_type=offline&code_challenge=17oCQTrzCaGDxzKAPP5atqNuM5nd74wNPOnWNb_XXic&code_challenge_method=S256&token_usage=remote"

2022-10-11 09:57:11,654 INFO     ___FILE_ONLY___ 


2022-10-11 09:57:53,033 ERROR    root            There was a problem with web authentication.
2022-10-11 09:57:53,045 DEBUG    root            (gcloud.auth.application-default.login) The provided authorization response is invalid. Expect a url with query parameters of [state, code, scope].
Traceback (most recent call last):
  File "/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/google-cloud-sdk/lib/surface/auth/application_default/login.py", line 137, in Run
    creds = auth_util.DoInstalledAppBrowserFlowGoogleAuth(
  File "/google-cloud-sdk/lib/googlecloudsdk/api_lib/auth/util.py", line 303, in DoInstalledAppBrowserFlowGoogleAuth
    user_creds = NoBrowserFlowRunner(scopes, client_config).Run()
  File "/google-cloud-sdk/lib/googlecloudsdk/api_lib/auth/util.py", line 138, in Run
    return self._flow.Run(**kwargs)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/flow.py", line 231, in Run
    return self._Run(**kwargs)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/flow.py", line 542, in _Run
    _ValidateAuthResponse(auth_response)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/flow.py", line 470, in _ValidateAuthResponse
    raise AuthRequestFailedError(_AUTH_RESPONSE_ERR_MSG)
googlecloudsdk.core.credentials.flow.AuthRequestFailedError: The provided authorization response is invalid. Expect a url with query parameters of [state, code, scope].
2022-10-11 09:57:53,058 ERROR    root            (gcloud.auth.application-default.login) The provided authorization response is invalid. Expect a url with query parameters of [state, code, scope].
